"""
GoatRaw - Skill System
OpenClaw has SKILL.md files + ClawHub registry.
GoatRaw has SkillPacks stored in DB/Redis, installable per workspace.

A Skill is a composable, reusable agent behavior with:
- Name + description
- Tool sequence (steps)
- Input/output schema
- Optionally self-generated by the agent itself (OpenClaw's "self-improving" feature)
"""

import json
import logging
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional
from dataclasses import dataclass, field

from app.core.redis_client import get_redis
from app.services.llm_adapter import generate_json, ModelType

logger = logging.getLogger("goatraw.skills")


# ─── Skill Definition ──────────────────────────────────────────────────────────

@dataclass
class SkillStep:
    tool: str
    params_template: dict       # Can reference {input.field} or {step_N.output.field}
    description: str = ""
    condition: Optional[str] = None  # Skip step if condition false


@dataclass
class SkillDefinition:
    id: str
    name: str
    description: str
    category: str              # "lead_gen" | "research" | "outreach" | "monitoring" | "custom"
    steps: List[SkillStep]
    input_schema: dict
    output_schema: dict
    author: str = "system"
    is_public: bool = False
    version: str = "1.0.0"
    created_at: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    tags: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        d = self.__dict__.copy()
        d["steps"] = [s.__dict__ for s in self.steps]
        return d


# ─── Built-in Skills (SkillHub) ──────────────────────────────────────────────

BUILTIN_SKILLS: Dict[str, SkillDefinition] = {

    "lead_scraper": SkillDefinition(
        id="lead_scraper",
        name="Lead Scraper",
        description="Find business leads in a niche. Search → scrape sites → extract contacts",
        category="lead_gen",
        input_schema={"niche": "str", "location": "str", "count": "int"},
        output_schema={"leads": "list[{name, email, website, phone, description}]"},
        tags=["leads", "scraping", "b2b"],
        steps=[
            SkillStep(tool="search_web", params_template={"query": "{input.niche} companies in {input.location}", "num_results": 10}),
            SkillStep(tool="web_scrape", params_template={"url": "{step_0.results[0].url}"}, description="Scrape top result"),
            SkillStep(tool="extract_structured_data", params_template={
                "text": "{step_1.content}",
                "schema": {"company_name": "str", "email": "str", "phone": "str", "website": "str", "description": "str"}
            }),
        ]
    ),

    "email_outreach_draft": SkillDefinition(
        id="email_outreach_draft",
        name="Email Outreach Drafter",
        description="Draft personalised cold outreach emails based on company research",
        category="outreach",
        input_schema={"company_name": "str", "company_website": "str", "sender_name": "str", "value_prop": "str"},
        output_schema={"subject": "str", "body": "str", "personalization_notes": "str"},
        tags=["email", "outreach", "sales"],
        steps=[
            SkillStep(tool="web_scrape", params_template={"url": "{input.company_website}"}),
            SkillStep(tool="summarize_text", params_template={"text": "{step_0.content}", "max_length": 300}),
            SkillStep(tool="extract_structured_data", params_template={
                "text": "{step_1.summary}",
                "schema": {"pain_points": "list[str]", "industry": "str", "size_estimate": "str", "key_product": "str"}
            }),
        ]
    ),

    "competitor_intel": SkillDefinition(
        id="competitor_intel",
        name="Competitor Intelligence",
        description="Research a competitor: pricing, features, weaknesses, reviews",
        category="research",
        input_schema={"competitor_name": "str", "your_product": "str"},
        output_schema={"pricing": "str", "features": "list", "weaknesses": "list", "positioning": "str"},
        tags=["competitors", "research", "strategy"],
        steps=[
            SkillStep(tool="search_web", params_template={"query": "{input.competitor_name} pricing features reviews 2025"}),
            SkillStep(tool="web_scrape", params_template={"url": "{step_0.results[0].url}"}),
            SkillStep(tool="search_web", params_template={"query": "{input.competitor_name} reviews complaints problems"}),
            SkillStep(tool="extract_structured_data", params_template={
                "text": "{step_1.content}",
                "schema": {"pricing_tiers": "list", "main_features": "list", "known_issues": "list", "target_market": "str"}
            }),
        ]
    ),

    "market_pulse": SkillDefinition(
        id="market_pulse",
        name="Market Pulse Monitor",
        description="Monitor news, trends, and sentiment for a market or keyword",
        category="monitoring",
        input_schema={"keyword": "str", "timeframe": "str"},
        output_schema={"top_news": "list", "sentiment": "str", "trending_topics": "list"},
        tags=["monitoring", "news", "trends"],
        steps=[
            SkillStep(tool="search_web", params_template={"query": "{input.keyword} news trends {input.timeframe}"}),
            SkillStep(tool="search_web", params_template={"query": "{input.keyword} startup funding 2025"}),
            SkillStep(tool="extract_structured_data", params_template={
                "text": "{step_0.results}",
                "schema": {"headlines": "list[str]", "sentiment": "positive|neutral|negative", "key_themes": "list[str]"}
            }),
        ]
    ),

    "website_audit": SkillDefinition(
        id="website_audit",
        name="Website Auditor",
        description="Audit a website for SEO, copy quality, CTA, and conversion issues",
        category="research",
        input_schema={"url": "str"},
        output_schema={"seo_issues": "list", "copy_quality": "str", "cta_effectiveness": "str", "recommendations": "list"},
        tags=["seo", "audit", "website"],
        steps=[
            SkillStep(tool="web_scrape", params_template={"url": "{input.url}"}),
            SkillStep(tool="extract_structured_data", params_template={
                "text": "{step_0.content}",
                "schema": {
                    "title": "str", "meta_description": "str",
                    "h1_tags": "list[str]", "call_to_action": "str",
                    "value_proposition": "str", "missing_elements": "list[str]"
                }
            }),
        ]
    ),
}


# ─── Skill Registry ────────────────────────────────────────────────────────────

class SkillRegistry:
    """
    Manages skills per workspace.
    Built-in skills always available.
    Custom skills stored in Redis per workspace.
    """

    PREFIX = "goatraw:skills:"

    async def list_skills(self, workspace_id: str) -> List[dict]:
        """List all skills available to a workspace."""
        skills = list(BUILTIN_SKILLS.values())

        # Load custom workspace skills
        r = get_redis()
        custom_key = f"{self.PREFIX}{workspace_id}"
        raw_list = await r.lrange(custom_key, 0, -1)
        for raw in raw_list:
            data = json.loads(raw)
            steps = [SkillStep(**s) for s in data.pop("steps", [])]
            skills.append(SkillDefinition(steps=steps, **data))

        return [s.to_dict() for s in skills]

    async def get_skill(self, skill_id: str, workspace_id: str = None) -> Optional[SkillDefinition]:
        if skill_id in BUILTIN_SKILLS:
            return BUILTIN_SKILLS[skill_id]

        if workspace_id:
            r = get_redis()
            custom_key = f"{self.PREFIX}{workspace_id}"
            raw_list = await r.lrange(custom_key, 0, -1)
            for raw in raw_list:
                data = json.loads(raw)
                if data.get("id") == skill_id:
                    steps = [SkillStep(**s) for s in data.pop("steps", [])]
                    return SkillDefinition(steps=steps, **data)
        return None

    async def install_skill(self, workspace_id: str, skill_def: dict) -> str:
        """Install a custom skill to a workspace."""
        skill_id = skill_def.get("id") or str(uuid.uuid4())[:8]
        skill_def["id"] = skill_id
        r = get_redis()
        await r.lpush(f"{self.PREFIX}{workspace_id}", json.dumps(skill_def))
        logger.info(f"Skill {skill_id} installed to workspace {workspace_id}")
        return skill_id

    async def generate_skill(self, workspace_id: str, description: str) -> SkillDefinition:
        """
        Self-improving feature: Agent generates a new skill from natural language description.
        Equivalent to OpenClaw's autonomous skill creation.
        """
        from app.agents.tools import get_tool_descriptions

        prompt = f"""You are GoatRaw's skill architect. Create a new skill from this description:

"{description}"

Available tools:
{get_tool_descriptions()}

Generate a skill definition as JSON:
{{
  "name": "...",
  "description": "...",
  "category": "lead_gen|research|outreach|monitoring|custom",
  "input_schema": {{"field": "type"}},
  "output_schema": {{"field": "type"}},
  "tags": [],
  "steps": [
    {{
      "tool": "tool_name",
      "params_template": {{"param": "{{input.field}}"}},
      "description": "what this step does"
    }}
  ]
}}

Use {{input.field}} to reference inputs and {{step_N.output.field}} to chain step outputs.
Make it practical and immediately executable."""

        result = await generate_json(prompt, model_type=ModelType.SMART)
        result["id"] = str(uuid.uuid4())[:8]
        result["author"] = f"ai_generated:{workspace_id}"
        result["version"] = "1.0.0"
        result["created_at"] = datetime.utcnow().isoformat()

        steps = [SkillStep(**s) for s in result.pop("steps", [])]
        skill = SkillDefinition(steps=steps, **result)

        # Auto-install to workspace
        skill_dict = skill.to_dict()
        await self.install_skill(workspace_id, skill_dict)
        logger.info(f"AI-generated skill '{skill.name}' created for workspace {workspace_id}")
        return skill


skill_registry = SkillRegistry()
